Repository calculation-methods/M8O-408B-20, pull requests merged in 2024-01, with the labels that each got.

#2 Popov/lab05
  popov/lab05/cmd/main.go
  popov/lab05/doc/img/img01.png
  popov/lab05/doc/img/img02.png
  popov/lab05/doc/report.pdf
  popov/lab05/doc/report.tex
  popov/lab05/go.mod
  popov/lab05/internal/analytical/analytical.go
  popov/lab05/internal/config/config.go
  popov/lab05/internal/crank_nicolson/crank_nicolson.go
  popov/lab05/internal/explicit_finite_difference/explicit_finite_difference.go
  popov/lab05/internal/implicit_finite_difference/implicit_finite_difference.go
  popov/lab05/lab05.ipynb
  popov/lab05/pkg/tools/tools.go
  popov/lab05/pkg/tools/tridiag_solve.go
Labels: ЛР1, Полностью

#4 Fattyakhetdinov/lab05
  fattyakhetdinov/.gitignore
  fattyakhetdinov/lab05/doc/report.docx
  fattyakhetdinov/lab05/doc/report.pdf
  fattyakhetdinov/lab05/src/graphics.ipynb
  fattyakhetdinov/lab05/src/main.cpp
Labels: ЛР1, Полностью

#5 Morozov/lab05
  morozov/.gitignore
  morozov/lab05/doc/report.docx
  morozov/lab05/doc/report.pdf
  morozov/lab05/src/.vscode/settings.json
  morozov/lab05/src/lab5.go
  morozov/lab05/src/lab5.ipynb
Labels: ЛР1, Полностью

#13 Zubko/lab05
  Zubko/lab5/functions.py
  Zubko/lab5/main.py
  Zubko/lab5/report.pdf
  Zubko/lab5/show.py
  Zubko/lab5/task.py
Labels: ЛР1, Полностью

#15 Borisov/lab05
  .gitignore
  borisov/lab5/draw_results.py
  borisov/lab5/functions.py
  borisov/lab5/main.py
  borisov/lab5/report.pdf
Labels: ЛР1, Полностью

#16 Zubko/lab06
  Zubko/lab6/functions.py
  Zubko/lab6/main.py
  Zubko/lab6/report.pdf
  Zubko/lab6/show.py
  Zubko/lab6/task.py
Labels: ЛР2, Полностью

#21 Popov/lab06
  popov/lab06/cmd/main.go
  popov/lab06/doc/img/img01.png
  popov/lab06/doc/img/img02.png
  popov/lab06/doc/report.pdf
  popov/lab06/doc/report.tex
  popov/lab06/go.mod
  popov/lab06/internal/analytical/analytical.go
  popov/lab06/internal/config/config.go
  popov/lab06/internal/explicit_finite_difference/explicit_finite_difference.go
  popov/lab06/internal/implicit_finite_difference/implicit_finite_difference.go
  popov/lab06/lab06.ipynb
  popov/lab06/pkg/tools/tools.go
  popov/lab06/pkg/tools/tridiag_solve.go
Labels: ЛР2, Полностью

#22 Prokhorov/lab5
  prokhorov/lab5/doc/Отчёт.docx
  prokhorov/lab5/doc/Отчёт.pdf
  prokhorov/lab5/src/5.cpp
  prokhorov/lab5/src/graphics.ipynb
Labels: ЛР1, Полностью

#27 Shandryuk/lab05
  shandryuk/.gitignore
  shandryuk/lab05/doc/report.docx
  shandryuk/lab05/doc/report.pdf
  shandryuk/lab05/src/crank_nicholson.cpp
  shandryuk/lab05/src/explicit.cpp
  shandryuk/lab05/src/graphics.py
  shandryuk/lab05/src/implicit.cpp
Labels: ЛР1, Полностью

#32 Marinin/lab5
  marinin/Lab_5/NM_lab_5.pdf
  marinin/Lab_5/lab_5.ipynb
Labels: ЛР1, Полностью

#37 Molchanov/lab5
  molchanov/lab5_NM.ipynb
  molchanov/report.pdf
Labels: ЛР1, Полностью

#80 Shandryuk/lab 07
  shandryuk/lab07/doc/Лабораторная работа 7.docx
  shandryuk/lab07/doc/Лабораторная работа 7.pdf
  shandryuk/lab07/src/graphics.py
  shandryuk/lab07/src/libman.cpp
  shandryuk/lab07/src/prost_iter.cpp
  shandryuk/lab07/src/zeidel.cpp
Labels: ЛР3, Полностью

#65 Fattyakhetdinov/lab07
  fattyakhetdinov/lab07/doc/report.docx
  fattyakhetdinov/lab07/doc/report.pdf
  fattyakhetdinov/lab07/src/lab7.ipynb
Labels: ЛР3, Полностью

#28 Zubko/lab7
  Zubko/lab7/functions.py
  Zubko/lab7/main.py
  Zubko/lab7/report.pdf
  Zubko/lab7/show.py
  Zubko/lab7/task.py
Labels: ЛР3, Полностью

#26 Prokhorov/lab7
  prokhorov/lab7/doc/Отчёт.docx
  prokhorov/lab7/doc/Отчёт.pdf
  prokhorov/lab7/src/7.cpp
  prokhorov/lab7/src/graphics.ipynb
Labels: ЛР3, Полностью

#25 Popov/lab07
  popov/lab07/cmd/main.go
  popov/lab07/doc/img/img01.png
  popov/lab07/doc/img/img02.png
  popov/lab07/doc/report.pdf
  popov/lab07/doc/report.tex
  popov/lab07/go.mod
  popov/lab07/internal/config/config.go
  popov/lab07/internal/finite_difference/finite_difference.go
  popov/lab07/internal/model/result_data.go
  popov/lab07/lab07.ipynb
  popov/lab07/pkg/tools/tools.go
Labels: ЛР3, Полностью

#19 Morozov/lab07
  morozov/lab07/doc/report.pdf
  morozov/lab07/src/lab7.py
Labels: ЛР3, Полностью

#79 Shandryuk/lab 06
  shandryuk/lab06/doc/Лабораторная работа 6.docx
  shandryuk/lab06/doc/Лабораторная работа 6.pdf
  shandryuk/lab06/src/2_1.cpp
  shandryuk/lab06/src/2_2.cpp
  shandryuk/lab06/src/3_2.cpp
Labels: ЛР2, Полностью

#33 Marinin/lab6
  marinin/Lab_6/NM_lab_6.pdf
  marinin/Lab_6/lab_6.ipynb
Labels: ЛР2, Полностью

#38 Molchanov/lab6
  NM_lab_6_╨┤╨╗╤П_╨Т╨╗╨░╨┤╨░.pdf
  lab6_NM.ipynb
Labels: ЛР2

#43 Borisov/lab06
  borisov/lab6/__pycache__/functions.cpython-311.pyc
  borisov/lab6/__pycache__/objects.cpython-311.pyc
  borisov/lab6/functions.py
  borisov/lab6/main.py
  borisov/lab6/objects.py
  borisov/lab6/plot.png
  borisov/lab6/report.docx
  borisov/lab6/report.pdf
Labels: ЛР2, Полностью

#64 Fattyakhetdinov/lab06
  fattyakhetdinov/lab06/doc/report.docx
  fattyakhetdinov/lab06/doc/report.pdf
  fattyakhetdinov/lab06/src/lab6.ipynb
Labels: ЛР2, Полностью

#81 Shandryuk/lab 08
  shandryuk/lab08/doc/Лабораторная работа 8.docx
  shandryuk/lab08/doc/Лабораторная работа 8.pdf
  shandryuk/lab08/src/graphics.py
  shandryuk/lab08/src/main.cpp
Labels: ЛР4, Полностью

#36 Popov/lab08
  popov/lab08/app/analytical.py
  popov/lab08/app/fractional_steps.py
  popov/lab08/app/plotting.py
  popov/lab08/app/tridiagonal_solve.py
  popov/lab08/app/variable_directions.py
  popov/lab08/doc/img/img01.png
  popov/lab08/doc/img/img02.png
  popov/lab08/doc/report.pdf
  popov/lab08/doc/report.tex
  popov/lab08/main.py
  popov/lab08/requirements.txt
Labels: ЛР4, Полностью

#34 Zubko/lab8
  Zubko/lab8/functions.py
  Zubko/lab8/main.py
  Zubko/lab8/report.pdf
  Zubko/lab8/show.py
  Zubko/lab8/task.py
Labels: ЛР4, Полностью

#31 Prokhorov/lab8
  prokhorov/lab8/doc/Отчёт.docx
  prokhorov/lab8/doc/Отчёт.pdf
  prokhorov/lab8/src/8.cpp
  prokhorov/lab8/src/graphics.ipynb
Labels: ЛР4, Полностью

#30 Morozov/lab08
  morozov/lab08/doc/report.pdf
  morozov/lab08/src/lab8.py
Labels: ЛР4, Полностью

#70 Borisov/lab07
  .gitignore
  borisov/lab7/Lab7.java
  borisov/lab7/lab7.pdf
Labels: ЛР3, Полностью

#50 Prokhorov/CP
  prokhorov/cp/doc/Отчёт.docx
  prokhorov/cp/doc/Отчёт.pdf
  prokhorov/cp/src/Volterra2.cpp
  prokhorov/cp/src/graphics.ipynb
Labels: Полностью

#68 Fattyakhetdinov/cp
  fattyakhetdinov/cp/doc/report.docx
  fattyakhetdinov/cp/doc/report.pdf
  fattyakhetdinov/cp/src/cp.ipynb
  fattyakhetdinov/cp/src/generate_matrix.py
  fattyakhetdinov/cp/src/matrix.txt
  fattyakhetdinov/cp/src/matrix2.txt
Labels: Полностью

#93 Marinin/CP
  marinin/CP/CP.ipynb
  marinin/CP/NM_CP.pdf
Labels: Полностью

#102 shandryuk/cp
  shandryuk/cp/doc/kp.docx
  shandryuk/cp/doc/kp.pdf
  shandryuk/cp/src/generate_matrix.py
  shandryuk/cp/src/main.cpp
Labels: Полностью

#120 Marinin/lab7
  marinin/Lab_7/NM_lab_7.pdf
  marinin/Lab_7/lab_7.ipynb
Labels: ЛР3, Полностью
